---
- name: Set up and deploy the application
  hosts: all
  become: yes
  tasks:

    - name: Install system dependencies
      apt:
        name: 
          - python3
          - python3-venv
          - python3-pip
          - git
        state: present
        update_cache: yes

    - name: Clone the repository
      git:
        repo: "https://github.com/CodeSSRockMan/DevOps_MedicalAppointmentsAPI.git"
        dest: "/opt/app"
        version: master

    - name: Create a virtual environment
      command: python3 -m venv /opt/app/.venv
      args:
        creates: /opt/app/.venv

    - name: Install Python dependencies
      shell: |
        source /opt/app/.venv/bin/activate
        pip install --upgrade pip
        pip install -r /opt/app/requirements.txt
      args:
        executable: /bin/bash

    - name: Upgrade Flask and Werkzeug
      shell: |
        source /opt/app/.venv/bin/activate
        pip install --upgrade flask werkzeug
      args:
        executable: /bin/bash

    - name: Run the application
      shell: |
        source /opt/app/.venv/bin/activate
        python /opt/app/app.py
      args:
        executable: /bin/bash
