version: '3'

services:
  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - RDS_HOST=${RDS_HOST}
      - RDS_USER=${RDS_USER}
      - RDS_PASSWORD=${RDS_PASSWORD}
      - DB_NAME=${db-softserve-project}
    restart: unless-stopped