- name: Secure Jenkins installation with IAM and SSM
  hosts: all
  become: yes
  vars:
    jenkins_port: 8080
    ssm_parameter_name: "/jenkins/admin_password"

  tasks:
    - name: Ensure apt cache is updated
      apt:
        update_cache: yes

    - name: Install system dependencies
      apt:
        name:
          - openjdk-11-jdk
          - gnupg2
          - curl
          - unzip
          - awscli
        state: present

    - name: Add Jenkins GPG key
      apt_key:
        url: https://pkg.jenkins.io/debian-stable/jenkins.io.key
        state: present

    - name: Add Jenkins repository
      apt_repository:
        repo: deb https://pkg.jenkins.io/debian-stable binary/
        state: present

    - name: Install Jenkins
      apt:
        name: jenkins
        state: present
        update_cache: yes

    - name: Enable and start Jenkins service
      systemd:
        name: jenkins
        enabled: yes
        state: started

    - name: Retrieve Jenkins admin password from SSM
      shell: |
        aws ssm get-parameter \
          --name {{ ssm_parameter_name }} \
          --with-decryption \
          --query "Parameter.Value" \
          --output text
      register: jenkins_password

    - name: Set Jenkins admin password (placeholder for future setup)
      debug:
        msg: "Jenkins admin password retrieved securely: {{ jenkins_password.stdout }}"

    - name: Ensure port {{ jenkins_port }} is allowed in UFW (optional)
      ufw:
        rule: allow
        port: "{{ jenkins_port }}"
        proto: tcp
      when: ansible_os_family == "Debian"

    - name: Print Jenkins URL
      debug:
        msg: "Jenkins is available at http://{{ ansible_host }}:{{ jenkins_port }}"

  # Note: You must associate this EC2 instance with an IAM Role that has permissions:
  # - ssm:GetParameter
  # - kms:Decrypt (if encrypted)

  # Security Group must allow TCP traffic on port 8080 from trusted IPs.
