- name: Deploy Flask App with Docker
  hosts: all
  become: yes

  vars:
    app_repo: "https://github.com/CodeSSRockMan/DevOps_MedicalAppointmentsAPI.git"
    app_dir: "/opt/app"
    docker_image_name: "medical_flask_app"
    docker_container_name: "medical_container"
    env_file_path: "/opt/app/.env"
    db_password_param: "/rds/mysql/password"  # SSM Parameter Store name

  tasks:
    - name: Install required system packages
      apt:
        name: [ "docker.io", "python3-pip", "git", "awscli" ]
        state: present
        update_cache: yes

    - name: Ensure Docker service is running
      service:
        name: docker
        state: started
        enabled: true

    - name: Clone the repository
      git:
        repo: "{{ app_repo }}"
        dest: "{{ app_dir }}"
        version: master
        force: yes

    - name: Fetch DB password from AWS SSM Parameter Store
      command: >
        aws ssm get-parameter --name "{{ db_password_param }}" --with-decryption --query 'Parameter.Value' --output text
      register: db_password_result

    - name: Create .env file for Docker container
      copy:
        dest: "{{ env_file_path }}"
        content: |
          DB_PASSWORD={{ db_password_result.stdout }}
      no_log: true

    - name: Stop and remove previous Docker container if exists
      docker_container:
        name: "{{ docker_container_name }}"
        state: absent
        force_kill: true

    - name: Build Docker image from source
      docker_image:
        name: "{{ docker_image_name }}"
        path: "{{ app_dir }}"
        build: true

    - name: Run the Docker container
      docker_container:
        name: "{{ docker_container_name }}"
        image: "{{ docker_image_name }}"
        state: started
        restart_policy: always
        ports:
          - "80:5000"
        env_file: "{{ env_file_path }}"
